version: '2.1'
services:
  redis:
    build: ./redis
    healthcheck:
      test: ["CMD-SHELL", "docker-healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
  viper-db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U viper"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: viper
      POSTGRES_USER: viper
  pit-db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pit"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: pit
      POSTGRES_USER: pit
  flower:
    build: ./flower
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5555/"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy
    ports:
     - "5555:5555"
  viper:
    build: ./viper
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/test"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5556:8080"
      - "5559:9090"
    depends_on:
      viper-db:
        condition: service_healthy
  ragpicker:
    build: ./ragpicker
    environment:
      BROKER_URL: redis://redis:6379/0
    depends_on:
      viper:
          condition: service_healthy
  pit:
    build: ./pit
    environment:
      PIT_DB: postgresql://pit:pit@pit-db:5432/pit
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/item"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      pit-db:
        condition: service_healthy
    ports:
      - "5558:5000"
  snake:
    build: ./snake
    environment:
      BROKER_URL: redis://redis:6379/0
      PIT_URL: http://pit:5000/
      VIPER_URL: http://viper:8080/
    depends_on:
      redis:
        condition: service_healthy
      pit:
        condition: service_healthy
      viper:
        condition: service_healthy
  handler:
      build: ./handler
      environment:
        BROKER_URL: redis://redis:6379/0
        PIT_URL: http://pit:5000/
        VIPER_URL: http://viper:8080/
      depends_on:
        redis:
          condition: service_healthy
        pit:
          condition: service_healthy
        viper:
          condition: service_healthy
  swagger:
    image: schickling/swagger-ui:latest
    depends_on:
      - pit
    environment:
      API_URL: http://localhost:5558/swagger.json
    ports:
      - "5557:80"
