version: '2'
services:
  redis:
    image: redis:latest
  viper-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: viper
      POSTGRES_USER: viper
  pit-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pit
      POSTGRES_USER: pit
  flower:
    build: ./flower
    depends_on:
      - redis
    ports:
     - "5555:5555"
  viper:
    build: ./viper
    ports:
      - "5556:8080"
    depends_on:
      - viper-db
  ragpicker:
    build: ./ragpicker
    environment:
      BROKER_URL: redis://redis:6379/0
    depends_on:
      - viper
  pit:
    build: ./pit
    environment:
      PIT_DB: postgresql://pit:pit@pit-db:5432/pit
    depends_on:
      - pit-db
    ports:
      - "5558:5000"
  swagger:
    image: schickling/swagger-ui:latest
    depends_on:
      - pit
    environment:
      API_URL: http://localhost:5558/swagger.json
    ports:
      - "5557:80"
